### ISSUE TITLE
A bug in qpp::applyCTRL()  function

### ISSUE THREAD

**Issue by titas99** [vsoftco/qpp#29]
Hi,

I want to report a bug in qpp::applyCTRL function, that there is a discrepancy in the behavior of the function regarding vectors and density matrices. Following is the code, that reproduces the bug.

    qpp::ket psi (8) ; //some random 3 qubit pure state
    // initialize psi
    qpp::cmat rho = psi*qpp::adjoint(psi); //density matrix

    qpp::cmat U (2,2) ; // some random unitary
    // initialize U
   
    auto A = qpp::applyCTRL(psi,U,{0,1},{2},{2,2,2}) ; // apply channel on pure state
    auto B = qpp::applyCTRL(rho,U,{0,1},{2},{2,2,2}) ; // apply channel on density matrix

    // Now A*adjoint(A) and B have to be equal. But from the code, they are not. Or may be, I am missing something much trivial.

I suspect the bug is in the density matrix part, and the pure state or vector part is absolutely fine.

**Comment by vsoftco** [comment]
Thanks for reporting. I will investigate the issue.

**Comment by vsoftco** [comment]
I can confirm it. Will fix it soon.

**Comment by titas99** [comment]
Thanks.

**Comment by vsoftco** [comment]
Fixed, new release v0.8.6. Thanks again for reporting it, please let me know if there are any additional issues with it. The error was indeed only present in the applyCTRL for density matrices, due some logical flaw in the code. After fixing I run some tests in ./examples/_test.cpp, and everything looks fine now.

**Comment by titas99** [comment]
Great!!!!

**Comment by vsoftco** [comment]
BTW there is one more issue in qpp::apply, which is based on qpp::applyCTRL (with control subsys set to empty vector, particular case that I forgot to change). I will fix it tomorrow and update the master (keeping the same release number).

**Comment by vsoftco** [comment]
Fixed in the master release also, unit testing added in ./unit_tests/testing.cpp

**Comment by titas99** [comment]
I can confirm it. Thanks!!!
