### ISSUE TITLE
`thread_local` return in singleton class

### ISSUE THREAD

**Issue by titaschanda** [vsoftco/qpp#35]
In `singleton.h` file, `get_thread_local_instance()` contains `thread_local` keyword in return type, like...
   
     thread_local static T& get_thread_local_instance()
        noexcept(std::is_nothrow_constructible<T>::value)
        {
            // Guaranteed to be destroyed.
            // Instantiated on first use.
            // Thread safe in C++11
            thread_local static T instance;

            return instance;
        }

I think `thread_local` keyword should be removed from the return type declaration, as the `instance` is already constructed as `thread_local` and thus it has `static` duration, and the function returns by its `static` ref. So the returned object is automatically becomes `thread_local`. Also `clang` complains about this keyword in the return type. I have removed the keyword, and it is working as it should be, like the following,

     static T& get_thread_local_instance() // no thread_local needed here
        noexcept(std::is_nothrow_constructible<T>::value)
        {
            // Guaranteed to be destroyed.
            // Instantiated on first use.
            // Thread safe in C++11
            thread_local static T instance;

            return instance;
        }

**Comment by vsoftco** [comment]
Thanks, you are absolutely right. Corrected it now on the last commit.
