### ISSUE TITLE
disp gives strangely-ordered vector

### ISSUE THREAD

**Issue by rumschuettel** [vsoftco/qpp#43]
Hi!
The following code:
```C
typedef std::complex<double> scalar;
void pretty_print(const qpp::ket& psi)
{	
    for (auto i = 0; i < psi.rows(); i++) {
        const scalar & v = psi(i);
        std::cout << std::bitset<8>(i++).to_string() << ": " <<  v << std::endl;
    }
}
```

gives a differently-ordered psi's as compared to `qpp::disp`, and it's not a simple reversed order, but some reshuffling I cannot decipher.
Why is that? What's the internal ordering `qpp::disp` prefers? I couldn't figure it out looking at your code.

Thanks!

**Comment by vsoftco** [comment]
@rumschuettel Why are you incrementing `i` twice?

**Comment by rumschuettel** [comment]
Indeed, this was my fault; my print function was quite a bit more complicated before and the double increment is a bug, which is super obvious after I posted it. My fault 👍 

Thanks a lot though!
