### ISSUE TITLE
Creating an entanglement between two separate qubits (kets)

### ISSUE THREAD

**Issue by ntwalibas** [vsoftco/qpp#51]
It appears I am unable to either understand the manual or be imaginative enough.  
I have two separate kets and I wish to create an entanglement between them.  
What I seek to accomplish is something akin to the snippet below:

```C++
qpp::ket ket1 = 0_ket;
qpp::ket ket2 = 0_ket;

// we apply the hadamard gate to the first ket
ket1 = qpp::gt.H * ket1;

// Now here, I want to apply CNOT between ket1 and ket2.
// In fact, in my use case, it can be any controlled gate between two kets.
qpp::ket result = applyCTRL(gt.CNOT, ket1, ket2); // I seek something similar to this
// Later, if I measure ket1, the state of ket2 should be automatically determined as expected of a Bell pair.
```

I'm using QPP in a project of mine at [Avalon PL](https://github.com/avalon-lang/avaloniq) where users declare qubits that are represented internally as kets so I'm trying to figure out how QPP is to handle things like entanglement between two separate variables.  
Any and all suggestions will be extremely useful.

**Comment by vsoftco** [comment]
You need to apply an entangling gate (like CNOT) on the Kronecker product of `ket1` and `ket2`, like

`qpp::ket result = applyCTRL(gt.CNOT, qpp::kron(ket1, ket2));`
