### ISSUE TITLE
Measurement of entangled qubits

### ISSUE THREAD

**Issue by ntwalibas** [vsoftco/qpp#52]
Say I have two qubits `psi_1` and `psi_2`. I entangle them and wish to measure them separately. Please consider the code below taken from example, slightly edited to illustrate my question:

```C++
// Measurements
// Source: ./examples/measurements.cpp
#include <iostream>
#include <tuple>

#include "qpp.h"

int main() {
    using namespace qpp;
    ket psi_1 = 0_ket;
    ket psi_2 = 0_ket;
    ket psi = kron(psi_1, psi_2);
    cmat U = gt.CNOT * kron(gt.H, gt.Id2);
    ket result = U * psi; // we have the Bell state (|00> + |11>) / sqrt(2)

    std::cout << ">> We just produced the Bell state:\n";
    std::cout << disp(result) << '\n';

    // measure the first qubit in the Z basis
    std::cout << "Measuring the first ket:\n";
    auto measured_one = measure(result, gt.Z, {0});
    std::cout << ">> Measurement result: " << std::get<0>(measured_one) << '\n';

    std::cout << "\n\nMeasuring the second ket:\n";
    auto measured_two = measure(result, gt.Z, {1});
    std::cout << ">> Measurement result: " << std::get<0>(measured_two) << '\n';
}
```
If the `psi_1` measurement result is <0>, `psi_2` measurement result must also be zero for a Bell-00 state.  
But if one runs the code above a few times, it will produce results were `psi_1` results in <0> while `psi_2` results in <1>.
I am aware that if I use `measure_seq` I can measure both at the same time and get consistent results but things get muddled quickly.

Is there a way to maintain consistency of results without having to measure all the subsystems at once using `measure_seq`?

**Comment by vsoftco** [comment]
The thing is that in your code you measure on independent copies of the Bell state (i.e. `result`). You need to use `measure_seq()`.

**Comment by ntwalibas** [comment]
Yeah, after reading the reference manual, I noticed that `measure_seq` was the only way forward. Thanks for confirming it.
