### ISSUE TITLE
Can gt.MODMUL be constructed with some universal quantum gate sets?

### ISSUE THREAD

**Issue by DevelopDaily** [vsoftco/qpp#59]
A simple Google search shows many papers about the universal quantum gates.

Can gt.MODMUL be constructed with some universal quantum gates? If impossible, constructing it with even simpler gates of the existing API would be better than the current implementation of the gt.MODMUL, which starts from scratch.

More general question is what criteria you use to include certain gates in the API. They don't seem to be built up from any universal quantum gates, do they?

**Comment by vsoftco** [comment]
Indeed the modular multiplication can be constructed out of a universal gate set. However the number of gates involved in the decomposition is quite large. The intention here is to have the gate "pre-defined", constructed from a relatively small number of gates (Rotations +H, following the construction in Nielsen & Chuang - Quantum Computation and Information). One can build its own with universal gates, which Quantum++ provides, such as the Clifford set + T gate, but again, that was not the intention here.
