### ISSUE TITLE
API doc images missing

### ISSUE THREAD

**Issue by DevelopDaily** [vsoftco/qpp#62]
I'd like to report some documentation errors. Well, I don't know if that is a doxygen problem or your problem.

A lot of images are missing. For example, I access the applyCTRL() API html doc and see the missing image pointing to qpp/doc/html/form_0.png, which does not exist. 

Please see the attached screenshot.

![images_missing](https://user-images.githubusercontent.com/54299975/67625842-71452480-f811-11e9-945d-7d7fd6182b6f.png)

**Comment by vsoftco** [comment]
Works fine for me, so I think it's a Doxygen problem. When you run Doxygen, are you getting any errors? Like "missing dot" or some other image processing tools? Here's how the page looks on my side, after running `doxygen`.
![Screen Shot 2019-10-26 at 5 10 56 PM](https://user-images.githubusercontent.com/6188943/67626030-dbf75f80-f813-11e9-8847-47bd6ac2276e.png)

**Comment by DevelopDaily** [comment]
Thank you for solving my Doxygen problem.

For those running the Ubuntu 19.04, the "dot" tool required by the Doxygen may not reside under /usr/local/bin, which is specified by default in the Doxyfile of the Quantum++. In my case, the tool is under /usr/bin

So, I modify the Doxyfile like this:

`DOT_PATH = /usr/bin`

**Comment by vsoftco** [comment]
@DevelopDaily Thanks! I then should remove the hard link to `dot` from the Doxyfile (although was automatically generated), and replace it probably with `/usr/bin/env dot`.
