### ISSUE TITLE
Just some feedback

### ISSUE THREAD

**Issue by DevelopDaily** [vsoftco/qpp#63]
After my evaluation of the design of your library and its API, I highly appreciate it, especially these design decisions, as you pointed out in your publication.

> ...library written in C++11 and composed solely of header files.

> The design is inspired from functional programming...

> You may extend it to incorporate graphical input, ... or build a more sophisticated library on top of it.

When I think about the header-only approach, I believe **all** the open source C/C++ library projects ought to be header-only. I am afraid those library developers who reject the header-only doctrine have forgotten why the header-source separation concept was introduced in the first place. When C was invented in 1972, there was no open source concept!

A lot of libraries have been contaminated heavily with GUI (Qt, etc., even worse with the Windows SDK) inadvertently or intentionally! Either way, that is a sin.

I am glad you offer a clean and sharp library. Equipped with the generous MIT license, that would enable the community to do a lot of good things in the years to come.

Thank you.

**Comment by vsoftco** [comment]
Thanks a lot for the feedback, glad you like it!
