### ISSUE TITLE
Would it be nice to have a to_QASM() function?

### ISSUE THREAD

**Issue by DevelopDaily** [vsoftco/qpp#64]
This function is very convenient.

`QCircuit qpp::qasm::read_from_file(const std::string& fname)`

Intuitively, however, one would expect its counterpart function -- something like this:

`void qpp::qasm::write_to_file(const std::string& fname, QCircuit qc) `

or 

`std::string QCircuit::to_QASM()` 

After all, it has already got a `to_JSON()`. Translation from JSON to QASM looks easy, but it is not trivial to get it done thoroughly. Would you please take the issue into consideration in the future releases?

One of my use cases is to have a distributed graphical interface to edit and test many QCircuit objects and save them to a QASM file when the testing is done. Then, I could run the QASM file in a physical quantum computer such as the IBM Q Experience.

As long as I can get the QASM, I can use this [tool](https://quantum-circuit.com/qasm2pyquil) to translate it to pyQuil and run it on Rigetti Quantum Cloud too.

**Comment by vsoftco** [comment]
I thought about this as well. The main issue is that `QCircuit` can do much more than QASM (e.g., higher dimensional systems (qudits), classical-quantum controls, shifted controls etc.) For this reason it's easy to do QASM -> QCircuit, but the other way around has a lot of particular cases and will make the whole process very tedious. Moreover, I don't intend to have QCircuit as a "universal language", but only use it inside the simulator.

**Comment by DevelopDaily** [comment]
That sounds reasonable. Thanks.
