### ISSUE TITLE
The implementation of the randrho()

### ISSUE THREAD

**Issue by DevelopDaily** [vsoftco/qpp#68]
Why bother to multiply the `randH(D)`  by 10? Did I miss something? Since all the elements in the matrix are of double data type, I seem unable to see the merits of the adjustment of the factor of 10.

I did a test. It produces the same final results with or without 10.

```
inline cmat randrho(idx D = 2) {
    //Exception handling...

    cmat result = 10 * randH(D);
    result = result * result.adjoint();

    return result / result.trace();
}
```

**Comment by vsoftco** [comment]
@DevelopDaily Absolutely true. The 10 there is from an old MATLAB code from Toby Cubitt http://www.dr-qubit.org/matlab/randRho.m Most likely it had to do with numerical stability, although it's not documented.
