### ISSUE TITLE
von Neumann entropy implementation

### ISSUE THREAD

**Issue by DevelopDaily** [vsoftco/qpp#69]
I notice the base of the logarithm in the `entropy()` is 2. It is also documented in the API as such.

`result -= ev(i) * std::log2(ev(i)); `

Many papers, however, tend to use the natural logarithm. So does the Qiskit.

I understand base 2, e, or 10 can be used to calculate entropy. Is your choice of the base 2 just a personal preference, or is it conceptually significant in the context of Quantum++?

**Comment by vsoftco** [comment]
I've used the convention used in Nielsen and Chuang (Sec. 11.1), in which they use `log_2`, to measure the entropy in "bits". With this convention, a maximally entangled state has entropy 1. I will document this in the Doxygen, thanks again for the code review!

**Comment by DevelopDaily** [comment]
Sounds great. Thanks.
